services:
  - type: web
    name: frontend
    env: static
    rootDir: apps/frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist

  - type: web
    name: backend
    env: node
    rootDir: apps/backend
    buildCommand: npm install
    startCommand: node server.js
