services:
  - type: web
    name: notes-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./apps/frontend/dist
    envVars:
      - key: NODE_VERSION
        value: 20.x
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
